export const DEFAULT_FLOORS = [
  "Basement",
  "Ground Floor",
  "First Floor",
  "Second Floor",
  "Terrace",
  "External",
] as const;

export const DEFAULT_STAGES = [
  "Planning & Approvals",
  "Site Preparation",
  "Excavation & Foundation",
  "Plinth",
  "RCC Structure",
  "Masonry / Brickwork",
  "Roofing / Slab",
  "Plastering",
  "Waterproofing",
  "Electrical Rough-in",
  "Plumbing Rough-in",
  "Doors & Windows",
  "Flooring & Tiling",
  "Painting",
  "Electrical Fixtures",
  "Plumbing Fixtures",
  "Woodwork / Interior",
  "Grills / Railings",
  "External Development",
  "Final Finishing",
] as const;

export const MATERIAL_CATALOG: { group: string; items: string[] }[] = [
  {
    group: "Civil / Structural",
    items: [
      "Cement",
      "Steel / TMT",
      "Ready Mix Concrete",
      "M-Sand",
      "River Sand",
      "Aggregate",
      "Bricks",
      "AAC Blocks",
      "Solid Cement Blocks",
      "Binding Wire",
      "Shuttering Material",
      "Construction Chemicals",
    ],
  },
  {
    group: "Foundation / Earthwork",
    items: [
      "Excavation",
      "Earth Filling",
      "Soil",
      "JCB",
      "Tractor",
      "PCC",
      "Footing",
      "Plinth",
      "Foundation Waterproofing",
    ],
  },
  {
    group: "Masonry",
    items: ["Bricks", "Blocks", "Mortar", "Lintel Materials", "Plastering Materials"],
  },
  {
    group: "RCC / Roofing",
    items: ["RCC", "Cement", "Steel", "RMC", "Shuttering", "Waterproofing", "Terrace Materials"],
  },
  {
    group: "Flooring",
    items: ["Floor Tiles", "Wall Tiles", "Granite", "Marble", "Skirting", "Tile Adhesive", "Grout"],
  },
  {
    group: "Doors / Windows",
    items: [
      "Main Door",
      "Internal Doors",
      "Door Frames",
      "Windows",
      "Glass",
      "UPVC",
      "Aluminium",
      "Locks",
      "Handles",
      "Hardware",
    ],
  },
  {
    group: "Wood / Interior",
    items: [
      "Teak",
      "Hardwood",
      "Plywood",
      "MDF",
      "WPC",
      "Modular Kitchen Materials",
      "Wardrobe Materials",
      "False Ceiling Materials",
    ],
  },
  {
    group: "Grills / Metal",
    items: [
      "Window Grills",
      "Main Gate",
      "Compound Gate",
      "Staircase Railing",
      "Balcony Railing",
      "MS Material",
      "SS Material",
    ],
  },
  {
    group: "Plumbing",
    items: [
      "CPVC",
      "UPVC",
      "PVC",
      "HDPE",
      "Pipes",
      "Fittings",
      "Valves",
      "Water Tank",
      "Sanitaryware",
      "Wash Basin",
      "WC",
      "Shower",
      "Taps",
      "Kitchen Sink",
      "Drainage Materials",
    ],
  },
  {
    group: "Electrical",
    items: [
      "Electrical Wire",
      "Conduit",
      "Switches",
      "Sockets",
      "MCB",
      "Distribution Board",
      "Earthing Material",
      "Light Fixtures",
      "Fans",
      "CCTV",
      "Network Wiring",
    ],
  },
  {
    group: "Painting",
    items: ["Putty", "Primer", "Interior Paint", "Exterior Paint", "Texture", "Waterproof Coating"],
  },
];

export const LABOUR_CATALOG: { group: string; items: string[] }[] = [
  {
    group: "Civil / Masonry Labour",
    items: [
      "Cement Work",
      "Brick Work",
      "Block Work",
      "Plastering",
      "RCC Work",
      "Foundation Work",
      "General Masonry",
    ],
  },
  {
    group: "Tile Labour",
    items: [
      "Floor Tile Laying",
      "Wall Tile Laying",
      "Bathroom Tile Work",
      "Kitchen Tile Work",
      "Granite Work",
      "Marble Work",
      "Skirting",
    ],
  },
  {
    group: "Wood Labour",
    items: [
      "Door Work",
      "Window Work",
      "Carpentry",
      "Modular Kitchen",
      "Wardrobe",
      "Furniture",
      "Interior Woodwork",
    ],
  },
  {
    group: "Grill / Fabrication Labour",
    items: [
      "Window Grills",
      "Main Gate",
      "Compound Gate",
      "Balcony Railing",
      "Staircase Railing",
      "MS Fabrication",
      "SS Fabrication",
      "Welding",
    ],
  },
  {
    group: "Electrical Labour",
    items: [
      "Wiring",
      "Conduit Installation",
      "Switch Installation",
      "Lighting Installation",
      "Fan Installation",
      "DB Installation",
      "Earthing",
      "CCTV Installation",
      "Network Installation",
    ],
  },
  {
    group: "Plumbing Labour",
    items: [
      "Pipe Work",
      "Bathroom Plumbing",
      "Kitchen Plumbing",
      "Drainage",
      "Water Tank",
      "Sanitaryware Installation",
    ],
  },
  {
    group: "Painting Labour",
    items: ["Putty", "Primer", "Interior Painting", "Exterior Painting", "Texture", "Waterproof Coating"],
  },
  {
    group: "Other Labour",
    items: ["General Labour", "Helper", "Cleaning", "Site Labour", "Contractor Labour"],
  },
];

export const SERVICE_CATALOG = [
  "JCB",
  "Excavator",
  "Tractor",
  "Transport",
  "Loading / Unloading",
  "Waste Removal",
  "Borewell",
  "Water Tanker",
  "Site Security",
  "Other Service",
] as const;

export const EQUIPMENT_CATALOG = [
  "Mixer Rental",
  "Scaffolding",
  "Cutting Machine Rental",
  "Vibrator",
  "Compactor",
  "Other Equipment",
] as const;

export const PROFESSIONAL_CATALOG = [
  "Architect",
  "Structural Engineer",
  "Civil Engineer",
  "Surveyor",
  "Soil Testing",
  "Plan Approval",
  "Government Fees",
  "Legal / Documentation",
  "Consultant",
] as const;

export const WORK_AREA_TEMPLATES: {
  name: string;
  materialNames: string[];
  labourNames: string[];
}[] = [
  {
    name: "Cement / Masonry",
    materialNames: [
      "Cement",
      "Bricks",
      "AAC Blocks",
      "Solid Cement Blocks",
      "Blocks",
      "Mortar",
      "Lintel Materials",
      "Plastering Materials",
      "Binding Wire",
      "Construction Chemicals",
      "M-Sand",
      "River Sand",
    ],
    labourNames: [
      "Cement Work",
      "Brick Work",
      "Block Work",
      "Plastering",
      "General Masonry",
      "Foundation Work",
    ],
  },
  {
    name: "RCC / Structure",
    materialNames: [
      "Steel / TMT",
      "Steel",
      "Ready Mix Concrete",
      "RMC",
      "RCC",
      "Aggregate",
      "Shuttering Material",
      "Shuttering",
    ],
    labourNames: ["RCC Work"],
  },
  {
    name: "Tiles",
    materialNames: [
      "Floor Tiles",
      "Wall Tiles",
      "Granite",
      "Marble",
      "Skirting",
      "Tile Adhesive",
      "Grout",
    ],
    labourNames: [
      "Floor Tile Laying",
      "Wall Tile Laying",
      "Bathroom Tile Work",
      "Kitchen Tile Work",
      "Granite Work",
      "Marble Work",
      "Skirting",
    ],
  },
  {
    name: "Wood",
    materialNames: [
      "Teak",
      "Hardwood",
      "Plywood",
      "MDF",
      "WPC",
      "Main Door",
      "Internal Doors",
      "Door Frames",
      "Windows",
      "Modular Kitchen Materials",
      "Wardrobe Materials",
      "False Ceiling Materials",
      "Locks",
      "Handles",
      "Hardware",
    ],
    labourNames: [
      "Door Work",
      "Window Work",
      "Carpentry",
      "Modular Kitchen",
      "Wardrobe",
      "Furniture",
      "Interior Woodwork",
    ],
  },
  {
    name: "Grills",
    materialNames: [
      "Window Grills",
      "Main Gate",
      "Compound Gate",
      "Staircase Railing",
      "Balcony Railing",
      "MS Material",
      "SS Material",
    ],
    labourNames: [
      "Window Grills",
      "Main Gate",
      "Compound Gate",
      "Balcony Railing",
      "Staircase Railing",
      "MS Fabrication",
      "SS Fabrication",
      "Welding",
    ],
  },
  {
    name: "Electrical",
    materialNames: [
      "Electrical Wire",
      "Conduit",
      "Switches",
      "Sockets",
      "MCB",
      "Distribution Board",
      "Earthing Material",
      "Light Fixtures",
      "Fans",
      "CCTV",
      "Network Wiring",
    ],
    labourNames: [
      "Wiring",
      "Conduit Installation",
      "Switch Installation",
      "Lighting Installation",
      "Fan Installation",
      "DB Installation",
      "Earthing",
      "CCTV Installation",
      "Network Installation",
    ],
  },
  {
    name: "Plumbing",
    materialNames: [
      "CPVC",
      "UPVC",
      "PVC",
      "HDPE",
      "Pipes",
      "Fittings",
      "Valves",
      "Water Tank",
      "Sanitaryware",
      "Wash Basin",
      "WC",
      "Shower",
      "Taps",
      "Kitchen Sink",
      "Drainage Materials",
    ],
    labourNames: [
      "Pipe Work",
      "Bathroom Plumbing",
      "Kitchen Plumbing",
      "Drainage",
      "Water Tank",
      "Sanitaryware Installation",
    ],
  },
  {
    name: "Painting",
    materialNames: ["Putty", "Primer", "Interior Paint", "Exterior Paint", "Texture", "Waterproof Coating"],
    labourNames: ["Putty", "Primer", "Interior Painting", "Exterior Painting", "Texture", "Waterproof Coating"],
  },
];
