export type StageConfig = {
  step: number;
  name: string;
  shortName: string;
  icon: string;
  phase: "STRUCTURAL" | "ROUGH_IN" | "FINISHING" | "INTERIORS";
  keywords: string[];
  recommendedMaterials: string[];
  recommendedLabours: string[];
  quickPresets: {
    label: string;
    type: "MATERIAL" | "LABOUR" | "SERVICE" | "EQUIPMENT" | "PROFESSIONAL" | "OTHER";
    categoryKeyword: string;
    description: string;
    unit?: string;
    quantity?: number;
    rate?: number;
    amount?: number;
    dailyWorkers?: number;
    dailyDays?: number;
  }[];
};

export const CHRONOLOGICAL_CONSTRUCTION_STAGES: StageConfig[] = [
  {
    step: 1,
    name: "Planning & Approvals",
    shortName: "Plan & Approval",
    icon: "",
    phase: "STRUCTURAL",
    keywords: ["plan", "approval", "architect", "engineer", "sanction"],
    recommendedMaterials: ["Construction Chemicals"],
    recommendedLabours: ["General Labour"],
    quickPresets: [
      {
        label: "Architectural Plan & 3D Elevation",
        type: "PROFESSIONAL",
        categoryKeyword: "architect",
        description: "House architectural drawings & 3D elevation fees",
        amount: 35000,
      },
      {
        label: "Structural Engineer Drawings",
        type: "PROFESSIONAL",
        categoryKeyword: "engineer",
        description: "Structural column and beam reinforcement drawings",
        amount: 20000,
      },
      {
        label: "Municipal / Authority Plan Sanction Fee",
        type: "PROFESSIONAL",
        categoryKeyword: "sanction",
        description: "Municipal building plan sanction and approval fee",
        amount: 50000,
      },
      {
        label: "Borewell Drilling & Casing Pipe",
        type: "SERVICE",
        categoryKeyword: "drilling",
        description: "Borewell drilling 600ft with 7\" PVC casing pipe",
        amount: 85000,
      },
    ],
  },
  {
    step: 2,
    name: "Site Preparation",
    shortName: "Site Prep",
    icon: "",
    phase: "STRUCTURAL",
    keywords: ["site", "prep", "demolition", "clearing", "shed"],
    recommendedMaterials: ["Binding Wire", "Construction Chemicals"],
    recommendedLabours: ["General Labour", "Helper"],
    quickPresets: [
      {
        label: "JCB Site Clearing & Leveling",
        type: "SERVICE",
        categoryKeyword: "jcb",
        description: "Site vegetation clearing, leveling and tree removal",
        amount: 12000,
      },
      {
        label: "Temporary Labour Shed & Store Room",
        type: "MATERIAL",
        categoryKeyword: "shuttering",
        description: "GI sheet shed setup for site cement storage & watchman",
        amount: 18000,
      },
      {
        label: "Temporary Electricity & Water Connection",
        type: "SERVICE",
        categoryKeyword: "transport",
        description: "Temporary power meter deposit and water connection",
        amount: 15000,
      },
    ],
  },
  {
    step: 3,
    name: "Excavation & Foundation",
    shortName: "Excavation & Footing",
    icon: "️",
    phase: "STRUCTURAL",
    keywords: ["excavation", "foundation", "footing", "pcc", "earthwork"],
    recommendedMaterials: ["Cement", "Steel / TMT / Binding Wire", "Sand", "Aggregates / Jelly"],
    recommendedLabours: ["Foundation Work", "General Masonry", "RCC Work"],
    quickPresets: [
      {
        label: "JCB Foundation Pit Excavation",
        type: "SERVICE",
        categoryKeyword: "jcb",
        description: "Column footing pits excavation (12 pits x 5ft depth)",
        amount: 18500,
      },
      {
        label: "PCC Bed Concrete Cement (50 Bags)",
        type: "MATERIAL",
        categoryKeyword: "cement",
        description: "UltraTech 53 Grade OPC Cement for PCC bed",
        unit: "bags",
        quantity: 50,
        rate: 390,
      },
      {
        label: "TMT Steel for Footing Mesh (1000 kg)",
        type: "MATERIAL",
        categoryKeyword: "steel",
        description: "TATA Tiscon 12mm Fe550D TMT Steel for Footing",
        unit: "kg",
        quantity: 1000,
        rate: 72,
      },
      {
        label: "Coarse Aggregate 40mm (2 Loads)",
        type: "MATERIAL",
        categoryKeyword: "aggregate",
        description: "40mm blue metal aggregate for footing PCC",
        unit: "loads",
        quantity: 2,
        rate: 14000,
      },
      {
        label: "Footing Concreting Mason Labour",
        type: "LABOUR",
        categoryKeyword: "foundation",
        description: "Footing PCC & column mesh concrete pouring labour",
        dailyWorkers: 4,
        dailyDays: 3,
        rate: 950,
      },
    ],
  },
  {
    step: 4,
    name: "Plinth",
    shortName: "Plinth Beam & Filling",
    icon: "",
    phase: "STRUCTURAL",
    keywords: ["plinth", "beam", "filling", "murrum", "compaction"],
    recommendedMaterials: ["Cement", "Steel / TMT / Binding Wire", "Sand", "Aggregates / Jelly"],
    recommendedLabours: ["Foundation Work", "RCC Work", "General Masonry"],
    quickPresets: [
      {
        label: "Plinth Beam TMT Steel (800 kg)",
        type: "MATERIAL",
        categoryKeyword: "steel",
        description: "JSW Neosteel 12mm & 16mm for Plinth Beam",
        unit: "kg",
        quantity: 800,
        rate: 72,
      },
      {
        label: "Murrum Earth Filling (6 Tractor Loads)",
        type: "SERVICE",
        categoryKeyword: "tractor",
        description: "Red soil / Murrum filling inside plinth area",
        unit: "loads",
        quantity: 6,
        rate: 2500,
      },
      {
        label: "Plinth Beam Shuttering & Casting Labour",
        type: "LABOUR",
        categoryKeyword: "rcc",
        description: "Plinth beam wooden shuttering, steel tying & concrete",
        dailyWorkers: 4,
        dailyDays: 4,
        rate: 950,
      },
    ],
  },
  {
    step: 5,
    name: "RCC Structure",
    shortName: "RCC Columns & Framework",
    icon: "️",
    phase: "STRUCTURAL",
    keywords: ["rcc", "column", "beam", "steel", "framework", "centering"],
    recommendedMaterials: ["Steel / TMT / Binding Wire", "Cement", "Sand", "Aggregates / Jelly", "Shuttering & Scaffolding"],
    recommendedLabours: ["RCC Work", "General Masonry"],
    quickPresets: [
      {
        label: "Column TMT Steel 16mm (1500 kg)",
        type: "MATERIAL",
        categoryKeyword: "steel",
        description: "TATA Tiscon 16mm Fe550D TMT Steel for Columns",
        unit: "kg",
        quantity: 1500,
        rate: 73,
      },
      {
        label: "Cement OPC 53 Grade (120 Bags)",
        type: "MATERIAL",
        categoryKeyword: "cement",
        description: "UltraTech 53 Grade OPC Cement for Columns & Beams",
        unit: "bags",
        quantity: 120,
        rate: 410,
      },
      {
        label: "Column Shuttering & Bar Bending Labour",
        type: "LABOUR",
        categoryKeyword: "rcc",
        description: "Column box shuttering, steel cage tying & vibration",
        dailyWorkers: 5,
        dailyDays: 6,
        rate: 950,
      },
    ],
  },
  {
    step: 6,
    name: "Roofing / Slab",
    shortName: "Roof Slab Casting",
    icon: "",
    phase: "STRUCTURAL",
    keywords: ["slab", "roof", "roofing", "casting", "rmc", "centering"],
    recommendedMaterials: ["Ready Mix Concrete (RMC)", "Steel / TMT / Binding Wire", "Cement", "Sand", "Waterproofing & Chemicals"],
    recommendedLabours: ["RCC Work", "General Masonry"],
    quickPresets: [
      {
        label: "Ready Mix Concrete M25 (RMC 24 Cum)",
        type: "MATERIAL",
        categoryKeyword: "ready",
        description: "RMC M25 Grade Concrete with Boom Pump for Slab",
        unit: "cum",
        quantity: 24,
        rate: 4600,
      },
      {
        label: "Roof Slab Steel Reinforcement (2000 kg)",
        type: "MATERIAL",
        categoryKeyword: "steel",
        description: "8mm & 10mm TMT Steel mesh for Roof Slab",
        unit: "kg",
        quantity: 2000,
        rate: 72,
      },
      {
        label: "Centering & Shuttering Labour (Slab)",
        type: "LABOUR",
        categoryKeyword: "rcc",
        description: "Centering plywood staging, prop fixing & slab casting",
        amount: 45000,
      },
      {
        label: "Dr.Fixit Waterproofing Compound for Slab",
        type: "MATERIAL",
        categoryKeyword: "chemical",
        description: "Dr.Fixit LW+ Integral Waterproofing Liquid (20L)",
        unit: "litres",
        quantity: 20,
        rate: 220,
      },
    ],
  },
  {
    step: 7,
    name: "Masonry / Brickwork",
    shortName: "Brick & Block Masonry",
    icon: "",
    phase: "STRUCTURAL",
    keywords: ["brick", "block", "masonry", "aac", "solid", "wall"],
    recommendedMaterials: ["Cement & AAC Blocks", "Red Bricks", "Cement", "Sand"],
    recommendedLabours: ["Block Work", "Brick Work", "General Masonry"],
    quickPresets: [
      {
        label: "Solid Concrete Blocks 6\" (800 Nos)",
        type: "MATERIAL",
        categoryKeyword: "block",
        description: "Solid Concrete Blocks 6 Inch (Outer Walls)",
        unit: "nos",
        quantity: 800,
        rate: 44,
      },
      {
        label: "Red Wirecut Bricks (2000 Nos)",
        type: "MATERIAL",
        categoryKeyword: "brick",
        description: "Red Wirecut Table-moulded Bricks for Partitions",
        unit: "nos",
        quantity: 2000,
        rate: 11,
      },
      {
        label: "Mortar M-Sand (1 Truck Load)",
        type: "MATERIAL",
        categoryKeyword: "sand",
        description: "M-Sand for Brick & Block Masonry Mortar",
        unit: "loads",
        quantity: 1,
        rate: 16000,
      },
      {
        label: "Mason & Helper Brickwork Wages",
        type: "LABOUR",
        categoryKeyword: "brick",
        description: "Daily Mason and Helper block wall construction",
        dailyWorkers: 4,
        dailyDays: 7,
        rate: 950,
      },
    ],
  },
  {
    step: 8,
    name: "Electrical Rough-in",
    shortName: "Conduit & Switch Boxes",
    icon: "",
    phase: "ROUGH_IN",
    keywords: ["electrical rough", "conduit", "chasing", "switch box", "wiring pipe"],
    recommendedMaterials: ["Conduit", "Electrical Wire", "Distribution Board"],
    recommendedLabours: ["Conduit Installation", "Wiring", "Electrical Labour"],
    quickPresets: [
      {
        label: "VIP Heavy PVC Conduit Pipes 25mm (50 Nos)",
        type: "MATERIAL",
        categoryKeyword: "conduit",
        description: "25mm Heavy Duty PVC Electrical Conduit Pipes & Bends",
        unit: "nos",
        quantity: 50,
        rate: 110,
      },
      {
        label: "Modular Metal Concealed Switch Boxes",
        type: "MATERIAL",
        categoryKeyword: "electrical",
        description: "GI Concealed Switch Boxes (12M, 8M, 6M, 4M, 2M)",
        unit: "nos",
        quantity: 35,
        rate: 95,
      },
      {
        label: "Wall Chipping & Conduit Laying Labour",
        type: "LABOUR",
        categoryKeyword: "electr",
        description: "Electrician wall groove cutting & pipe routing",
        dailyWorkers: 2,
        dailyDays: 5,
        rate: 950,
      },
    ],
  },
  {
    step: 9,
    name: "Plumbing Rough-in",
    shortName: "Concealed Water & Drain Pipes",
    icon: "",
    phase: "ROUGH_IN",
    keywords: ["plumbing rough", "cpvc", "upvc", "drainage", "water line", "concealed pipe"],
    recommendedMaterials: ["CPVC", "UPVC", "PVC", "Pipes", "Fittings"],
    recommendedLabours: ["Pipe Work", "Bathroom Plumbing", "Plumbing Labour"],
    quickPresets: [
      {
        label: "Astral CPVC Hot/Cold Pipes 1\" & 3/4\"",
        type: "MATERIAL",
        categoryKeyword: "cpvc",
        description: "Astral CPVC Pro SDR-11 Pipes with Brass Elbows & Tees",
        unit: "bundles",
        quantity: 4,
        rate: 3800,
      },
      {
        label: "Supreme 4\" UPVC Soil & Rainwater Pipes",
        type: "MATERIAL",
        categoryKeyword: "upvc",
        description: "Supreme 4\" & 2.5\" UPVC Drainage & Waste Pipes",
        unit: "nos",
        quantity: 12,
        rate: 750,
      },
      {
        label: "Concealed Bathroom Plumbing Labour",
        type: "LABOUR",
        categoryKeyword: "plumb",
        description: "Concealed wall chasing, diverter installation & testing",
        dailyWorkers: 2,
        dailyDays: 4,
        rate: 950,
      },
    ],
  },
  {
    step: 10,
    name: "Plastering",
    shortName: "Internal & External Plaster",
    icon: "️",
    phase: "ROUGH_IN",
    keywords: ["plaster", "plastering", "smooth", "sponge", "sandface"],
    recommendedMaterials: ["Cement", "Sand", "Waterproofing & Chemicals"],
    recommendedLabours: ["Plastering", "General Masonry"],
    quickPresets: [
      {
        label: "P-Sand / Plastering Sand (2 Truck Loads)",
        type: "MATERIAL",
        categoryKeyword: "sand",
        description: "Fine Washed P-Sand for Smooth Internal Plastering",
        unit: "loads",
        quantity: 2,
        rate: 18000,
      },
      {
        label: "Cement for Plastering (100 Bags)",
        type: "MATERIAL",
        categoryKeyword: "cement",
        description: "Birla Super / ACC PPC Cement for Plastering",
        unit: "bags",
        quantity: 100,
        rate: 395,
      },
      {
        label: "Chicken Mesh Wire Bundle for Joints",
        type: "MATERIAL",
        categoryKeyword: "binding",
        description: "GI Chicken Mesh Wire for Column-Brickwork Junctions",
        unit: "rolls",
        quantity: 6,
        rate: 650,
      },
      {
        label: "Internal & External Plastering Mason Wages",
        type: "LABOUR",
        categoryKeyword: "plaster",
        description: "Double coat external sponge plaster & smooth interior",
        dailyWorkers: 5,
        dailyDays: 8,
        rate: 1000,
      },
    ],
  },
  {
    step: 11,
    name: "Waterproofing",
    shortName: "Bathroom & Terrace Waterproofing",
    icon: "️",
    phase: "FINISHING",
    keywords: ["waterproof", "waterproofing", "sunken", "terrace", "sump"],
    recommendedMaterials: ["Waterproof Coating", "Construction Chemicals", "Cement"],
    recommendedLabours: ["Waterproof Coating", "General Masonry"],
    quickPresets: [
      {
        label: "Dr.Fixit Fastflex 2-Coat Waterproofing",
        type: "MATERIAL",
        categoryKeyword: "chemical",
        description: "Dr.Fixit Fastflex Polymer kit for Bathroom Sunken Slabs",
        unit: "kits",
        quantity: 4,
        rate: 3200,
      },
      {
        label: "Terrace Waterproof Coating Membrane (20L)",
        type: "MATERIAL",
        categoryKeyword: "waterproof",
        description: "Asian Paints Damp Proof Ultra Elastomeric Membrane",
        unit: "buckets",
        quantity: 3,
        rate: 4800,
      },
      {
        label: "Sunken Slab Waterproofing Labour",
        type: "LABOUR",
        categoryKeyword: "waterproof",
        description: "Surface cleaning, coving & 2 coats waterproofing labour",
        amount: 14000,
      },
    ],
  },
  {
    step: 12,
    name: "Doors & Windows",
    shortName: "Door Frames & Windows",
    icon: "",
    phase: "FINISHING",
    keywords: ["door", "window", "frame", "teak", "upvc", "glass"],
    recommendedMaterials: ["Main Door", "Internal Doors", "Door Frames", "Windows", "UPVC", "Aluminium"],
    recommendedLabours: ["Door Work", "Window Work", "Carpentry"],
    quickPresets: [
      {
        label: "Teak Wood Main Door Frame (5x3\")",
        type: "MATERIAL",
        categoryKeyword: "door",
        description: "First Quality Teak Wood Main Door Frame with Moulding",
        unit: "sets",
        quantity: 1,
        rate: 18500,
      },
      {
        label: "Salwood / Red Mirandi Bedroom Door Frames",
        type: "MATERIAL",
        categoryKeyword: "frame",
        description: "Seasoned Salwood Frames 4x2.5\" for 5 Bedrooms",
        unit: "sets",
        quantity: 5,
        rate: 4200,
      },
      {
        label: "UPVC Sliding Windows with Mosquito Mesh",
        type: "MATERIAL",
        categoryKeyword: "window",
        description: "Kommerling / Aparna UPVC 3-Track Sliding Windows",
        unit: "sqft",
        quantity: 180,
        rate: 480,
      },
      {
        label: "Door Frame Fixing & Alignment Labour",
        type: "LABOUR",
        categoryKeyword: "wood",
        description: "Carpenter frame fixing with holdfasts & grouting",
        amount: 8500,
      },
    ],
  },
  {
    step: 13,
    name: "Flooring & Tiling",
    shortName: "Tiles, Granite & Marble",
    icon: "",
    phase: "FINISHING",
    keywords: ["tile", "tiling", "granite", "marble", "flooring", "skirting", "adhesive"],
    recommendedMaterials: ["Floor Tiles", "Wall Tiles", "Granite", "Tile Adhesive", "Grout"],
    recommendedLabours: ["Floor Tile Laying", "Wall Tile Laying", "Granite Work", "Tile Labour"],
    quickPresets: [
      {
        label: "Vitrified Floor Tiles 4x2ft (Living/Bedrooms)",
        type: "MATERIAL",
        categoryKeyword: "tile",
        description: "Kajaria / Somany GVT 4x2ft Vitrified Glazed Floor Tiles",
        unit: "sqft",
        quantity: 800,
        rate: 65,
      },
      {
        label: "Bathroom Anti-Skid Floor & Wall Tiles",
        type: "MATERIAL",
        categoryKeyword: "wall tile",
        description: "Ceramic Wall Tiles 2x1ft & Anti-Skid Floor Tiles",
        unit: "sqft",
        quantity: 450,
        rate: 48,
      },
      {
        label: "Black Galaxy Kitchen Granite Slab",
        type: "MATERIAL",
        categoryKeyword: "granite",
        description: "Premium Black Galaxy Granite for Kitchen Countertop",
        unit: "sqft",
        quantity: 85,
        rate: 195,
      },
      {
        label: "Roff T01 Tile Adhesive (20kg Bags)",
        type: "MATERIAL",
        categoryKeyword: "adhesive",
        description: "Pidilite Roff Tile Adhesive 20kg Bags",
        unit: "bags",
        quantity: 25,
        rate: 340,
      },
      {
        label: "Tile Laying & Granite Moulding Labour",
        type: "LABOUR",
        categoryKeyword: "tile",
        description: "Skilled Tile Mason laying, spacer leveling & grouting",
        dailyWorkers: 3,
        dailyDays: 8,
        rate: 1100,
      },
    ],
  },
  {
    step: 14,
    name: "Painting",
    shortName: "Putty, Primer & Painting",
    icon: "",
    phase: "FINISHING",
    keywords: ["paint", "painting", "putty", "primer", "royale", "apex"],
    recommendedMaterials: ["Putty", "Primer", "Interior Paint", "Exterior Paint"],
    recommendedLabours: ["Putty", "Primer", "Interior Painting", "Exterior Painting", "Painting Labour"],
    quickPresets: [
      {
        label: "Birla White Wall Care Putty (40kg Bags)",
        type: "MATERIAL",
        categoryKeyword: "putty",
        description: "Birla White Waterproof Wall Care Putty (2-Coats)",
        unit: "bags",
        quantity: 15,
        rate: 880,
      },
      {
        label: "Asian Paints Decoprime Interior Primer (20L)",
        type: "MATERIAL",
        categoryKeyword: "primer",
        description: "Asian Paints Acrylic Wall Primer 20L Buckets",
        unit: "buckets",
        quantity: 4,
        rate: 1950,
      },
      {
        label: "Asian Paints Royale Luxury Emulsion (20L)",
        type: "MATERIAL",
        categoryKeyword: "interior",
        description: "Royale Luxury Emulsion Sheen Finish for Interior",
        unit: "buckets",
        quantity: 3,
        rate: 5900,
      },
      {
        label: "Asian Paints Apex Ultima Exterior Paint (20L)",
        type: "MATERIAL",
        categoryKeyword: "exterior",
        description: "Apex Ultima Weatherproof Exterior Paint",
        unit: "buckets",
        quantity: 3,
        rate: 5400,
      },
      {
        label: "Painting Contractor Labour (Putty + 2 Coats)",
        type: "LABOUR",
        categoryKeyword: "paint",
        description: "Full house sanding, 2 coats putty, primer & 2 paint coats",
        amount: 55000,
      },
    ],
  },
  {
    step: 15,
    name: "Electrical Fixtures",
    shortName: "Wiring, Lights & Switches",
    icon: "",
    phase: "FINISHING",
    keywords: ["electrical fixture", "wire", "switch", "light", "fan", "mcb"],
    recommendedMaterials: ["Electrical Wire", "Switches", "Sockets", "Light Fixtures", "Fans", "MCB"],
    recommendedLabours: ["Wiring", "Switch Installation", "Lighting Installation", "Electrical Labour"],
    quickPresets: [
      {
        label: "Finolex 1.5 & 2.5 sqmm FR Copper Wire Coils",
        type: "MATERIAL",
        categoryKeyword: "wire",
        description: "Finolex Flame Retardant Wire (Red, Black, Green, Blue)",
        unit: "coils",
        quantity: 8,
        rate: 1850,
      },
      {
        label: "Legrand Mylinc Modular Switches & Plates Set",
        type: "MATERIAL",
        categoryKeyword: "switch",
        description: "Modular Switches, 6A/16A Sockets & Cover Plates",
        amount: 28000,
      },
      {
        label: "LED Concealed Ceiling Lights & COB Lights",
        type: "MATERIAL",
        categoryKeyword: "light",
        description: "Philips 12W LED Concealed Downlights (Warm/Cool)",
        unit: "nos",
        quantity: 24,
        rate: 320,
      },
      {
        label: "Havells / Atomberg BLDC Ceiling Fans",
        type: "MATERIAL",
        categoryKeyword: "fan",
        description: "Energy Saving BLDC Fans with Remote Control",
        unit: "nos",
        quantity: 5,
        rate: 3400,
      },
      {
        label: "Electrician Wire Pulling & Fixture Fitting Labour",
        type: "LABOUR",
        categoryKeyword: "electr",
        description: "Wire pulling, DB dressing, switch and fan installation",
        amount: 22000,
      },
    ],
  },
  {
    step: 16,
    name: "Plumbing Fixtures",
    shortName: "Sanitaryware, Taps & Water Tank",
    icon: "",
    phase: "FINISHING",
    keywords: ["sanitary", "tap", "commode", "wash basin", "tank", "shower", "sink"],
    recommendedMaterials: ["Sanitaryware", "WC", "Wash Basin", "Taps", "Shower", "Water Tank", "Kitchen Sink"],
    recommendedLabours: ["Sanitaryware Installation", "Water Tank", "Plumbing Labour"],
    quickPresets: [
      {
        label: "Jaquar / Kohler CP Bathroom Tap Set & Diverters",
        type: "MATERIAL",
        categoryKeyword: "tap",
        description: "Basin mixers, overhead shower, health faucets & angle valves",
        amount: 32000,
      },
      {
        label: "Hindware / Cera Wall-Hung Commodes & Basins",
        type: "MATERIAL",
        categoryKeyword: "wc",
        description: "Wall hung WC with soft close seat & concealed cistern tanks",
        unit: "sets",
        quantity: 3,
        rate: 8500,
      },
      {
        label: "Nirali Stainless Steel Kitchen Sink with Drain",
        type: "MATERIAL",
        categoryKeyword: "sink",
        description: "304 Grade Heavy Stainless Steel Kitchen Sink (37x18\")",
        unit: "nos",
        quantity: 1,
        rate: 7200,
      },
      {
        label: "Sintex 1500L Triple Layer Overhead Water Tank",
        type: "MATERIAL",
        categoryKeyword: "tank",
        description: "1500 Litres Antibacterial Overhead Water Tank",
        unit: "nos",
        quantity: 1,
        rate: 11500,
      },
      {
        label: "Plumber Sanitaryware & Tap Installation Labour",
        type: "LABOUR",
        categoryKeyword: "sanitary",
        description: "Commode fixing, tap installation, geyser & tank connection",
        amount: 12000,
      },
    ],
  },
  {
    step: 17,
    name: "Woodwork / Interior",
    shortName: "Kitchen & Wardrobe Woodwork",
    icon: "🪵",
    phase: "INTERIORS",
    keywords: ["wood", "plywood", "laminate", "kitchen", "wardrobe", "cabinet", "interior"],
    recommendedMaterials: ["Plywood", "Modular Kitchen Materials", "Wardrobe Materials", "Hardwood", "Hardware"],
    recommendedLabours: ["Modular Kitchen", "Wardrobe", "Carpentry", "Wood Labour"],
    quickPresets: [
      {
        label: "Century BWP Marine Plywood 18mm (10 Sheets)",
        type: "MATERIAL",
        categoryKeyword: "plywood",
        description: "Century Sainik 710 Waterproof BWP Plywood 8x4ft",
        unit: "sheets",
        quantity: 10,
        rate: 2600,
      },
      {
        label: "Merino / Century Laminate Sheets 1mm",
        type: "MATERIAL",
        categoryKeyword: "wood",
        description: "Decorative Matte & Gloss 1mm Laminate Sheets",
        unit: "sheets",
        quantity: 12,
        rate: 1450,
      },
      {
        label: "Hettich Soft-Close Hinges & Drawer Channels",
        type: "MATERIAL",
        categoryKeyword: "hardware",
        description: "Kitchen tandem drawers and soft-close hinges kit",
        amount: 24000,
      },
      {
        label: "Modular Kitchen & Wardrobe Carpenter Labour",
        type: "LABOUR",
        categoryKeyword: "wood",
        description: "Plywood cutting, laminate pasting & modular box making",
        amount: 48000,
      },
    ],
  },
  {
    step: 18,
    name: "Grills / Railings",
    shortName: "Safety Grills & SS Railings",
    icon: "️",
    phase: "INTERIORS",
    keywords: ["grill", "railing", "gate", "ms", "ss", "fabrication"],
    recommendedMaterials: ["Window Grills", "Main Gate", "Staircase Railing", "Balcony Railing", "MS Material", "SS Material"],
    recommendedLabours: ["Window Grills", "Main Gate", "Balcony Railing", "MS Fabrication", "SS Fabrication"],
    quickPresets: [
      {
        label: "Window Safety Grills MS Fabrication",
        type: "MATERIAL",
        categoryKeyword: "grill",
        description: "12mm Bright MS Square Bar Window Safety Grills (Painted)",
        unit: "kg",
        quantity: 350,
        rate: 85,
      },
      {
        label: "Stainless Steel SS-304 Staircase Railing",
        type: "MATERIAL",
        categoryKeyword: "railing",
        description: "SS 304 Grade Staircase & Balcony Safety Railings",
        unit: "rft",
        quantity: 65,
        rate: 550,
      },
      {
        label: "Main Compound Gate Fabrication & Installation",
        type: "SERVICE",
        categoryKeyword: "gate",
        description: "Designer Heavy MS Compound Gate with Primer & Paint",
        amount: 32000,
      },
    ],
  },
  {
    step: 19,
    name: "External Development",
    shortName: "Compound, Paving & Sump",
    icon: "",
    phase: "INTERIORS",
    keywords: ["compound", "paving", "sump", "external", "drain", "gate"],
    recommendedMaterials: ["Solid Cement Blocks", "Cement", "M-Sand", "Aggregate"],
    recommendedLabours: ["General Masonry", "General Labour"],
    quickPresets: [
      {
        label: "Interlocking Paver Blocks for Driveway & Parking",
        type: "MATERIAL",
        categoryKeyword: "block",
        description: "Heavy 60mm Zigzag Interlocking Paver Blocks (400 sqft)",
        unit: "sqft",
        quantity: 400,
        rate: 42,
      },
      {
        label: "Underground RCC Sump Tank Construction",
        type: "SERVICE",
        categoryKeyword: "transport",
        description: "8000 Litres RCC Water Sump Tank Complete Work",
        amount: 65000,
      },
      {
        label: "Compound Wall Blockwork & Plastering",
        type: "LABOUR",
        categoryKeyword: "mason",
        description: "Compound boundary wall masonry and copings",
        amount: 28000,
      },
    ],
  },
  {
    step: 20,
    name: "Final Finishing",
    shortName: "Deep Cleaning & Handover",
    icon: "",
    phase: "INTERIORS",
    keywords: ["final", "finishing", "cleaning", "pooja", "handover", "touchup"],
    recommendedMaterials: ["Construction Chemicals"],
    recommendedLabours: ["Cleaning", "Helper", "General Labour"],
    quickPresets: [
      {
        label: "Full House Deep Cleaning & Acid Wash",
        type: "SERVICE",
        categoryKeyword: "waste",
        description: "Floor tile machine scrub, glass cleaning & debris removal",
        amount: 12000,
      },
      {
        label: "Final Paint Touchups & Snagging",
        type: "LABOUR",
        categoryKeyword: "paint",
        description: "Wall and door final finish touchups before Griha Pravesh",
        amount: 8000,
      },
      {
        label: "Griha Pravesh / House Warming Pooja Expenses",
        type: "OTHER",
        categoryKeyword: "other",
        description: "Pooja materials, tent, catering and site celebration",
        amount: 25000,
      },
    ],
  },
];

/**
 * Helper to get stage configuration by stage name or ID
 */
export function getStageConfig(stageNameOrId?: string | null): StageConfig | undefined {
  if (!stageNameOrId) return undefined;
  const lower = stageNameOrId.toLowerCase();
  return CHRONOLOGICAL_CONSTRUCTION_STAGES.find(
    (s) =>
      s.name.toLowerCase() === lower ||
      s.shortName.toLowerCase() === lower ||
      s.keywords.some((k) => lower.includes(k)) ||
      String(s.step) === stageNameOrId
  );
}

/**
 * Helper to get stage order number (1 to 20) for any stage name
 */
export function getStageOrderNumber(stageName?: string | null): number {
  if (!stageName) return 999;
  const config = getStageConfig(stageName);
  return config ? config.step : 999;
}

/**
 * Sorts any list of items by construction stage
 */
export function sortByConstructionStage<T extends { constructionStageName?: string | null; stageName?: string | null; name?: string | null }>(
  items: T[]
): T[] {
  return [...items].sort((a, b) => {
    const stageA = a.constructionStageName ?? a.stageName ?? a.name;
    const stageB = b.constructionStageName ?? b.stageName ?? b.name;
    return getStageOrderNumber(stageA) - getStageOrderNumber(stageB);
  });
}
